name: CI/CD

on:
  push:
    branches:
      - 10th

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "10th"
      - run: npm ci
      - run: npm run test
      - run: echo "success"
