name: CI/CD-11th

on:
  push:
    branches:
      - 11th
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "11th"
      - run: npm ci
